### ISSUE TITLE
'meteor publish' gives 'access denied'

### ISSUE THREAD

**Issue by hellogerard** [sebakerckhof/stratosphere#4]
I have Stratosphere successfully running (I believe). I went to publish my first private package. When I run `METEOR_PACKAGE_SERVER_URL=http://localhost:3000 meteor publish` in my package project, I get:

```
It looks like you have been logged out! Please log in with your Meteor developer account. If you don't have one,
you can quickly create one at www.meteor.com.
Username: hellogerard
Password:                                     

/Users/gerard/.meteor/packages-from-server/localhostX3000/meteor-tool/.1.1.9.qpd2pt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: access-denied
    at sendAuthorizeRequest (/tools/meteor-services/auth.js:351:11)
    at oauthFlow (/tools/meteor-services/auth.js:382:25)
    at Object.exports.loginWithTokenOrOAuth (/tools/meteor-services/auth.js:956:17)
    at Object.exports.loggedInConnection (/tools/meteor-services/auth-client.js:87:12)
    at Object.exports.loggedInPackagesConnection (/tools/packaging/package-client.js:232:21)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:305:32)
    at /tools/cli/main.js:1378:23
```

I have copied the modified `auth-client.js` file to the right place. I have meteor-tool@1.1.9, but it didn't  look like it was any different from 1.1.7.

**Comment by sebakerckhof** [comment]
Yeah, Actually you need to copy the modified auth-client file twice.
Meteor keeps the packages it downloads in a directory per package server. meteor-tool is handled the same way as any other meteor package.

This means, the first time you connect with the package server it will use meteor-tool from:

```
/Users/gerard/.meteor/packages/meteor-tool/...
```

Which is the directory for the default package server

Then as soon as you do some stuff with the new package server it will download meteor-tool again and put it in 

```
/Users/gerard/.meteor/packages-from-server/[packageserverurl]/meteor-tool/...
```

If you then run meteor again it will use meteor-tool from that location.
This means you have to copy auth-client.js also in that location.

I've found this too cumbersome too explain in the readme and was hoping I could fix the oAuth flow (which is why the modification is required) soon.

**Comment by hellogerard** [comment]
That worked. 

Now that I can get the OAuth error too, I will try to put some time into figuring out the issue.

I can now publish private packages, and see them on Stratosphere. But I am getting an error when trying to add it to a project. I will open a new issue.
